apiVersion: batch/v1
kind: Job
metadata:
  generateName: hook-dev-
  annotations:
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(10)"]
      restartPolicy: Never
  backoffLimit: 4
