apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-team-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zhongzhoucai/argocd.git
    targetRevision: HEAD
    path: yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team-1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
